stages:
  - build
  - deploy

yarn_build_dev:
  stage: build
  cache:
    key: npm
    paths:
      - ./src/node_modules
  script:
    - cd src
    - npm install
    - npm run build
  artifacts:
    expire_in: 1 month
    paths:
      - ./src/dist
  only:
    refs:
      - main
  tags:
    - dl-dev

.base_deploy: &base_deploy
  script:
    - sudo rm -Rf $PROJECT_PATH/builds/$CI_PIPELINE_ID
    - sudo cp -a ./src/dist $PROJECT_PATH/builds/$CI_PIPELINE_ID
    - sudo ln -sfn $PROJECT_PATH/builds/$CI_PIPELINE_ID/ $PROJECT_PATH/website
    - sudo chown -R $OWNER_USER:$OWNER_GROUP $PROJECT_PATH/builds
    - sudo chmod -R 777 $PROJECT_PATH/builds
    - cd $PROJECT_PATH/builds
    - shopt -s extglob
    - rm -rf !("$CI_PIPELINE_ID")

deploy_stage:
  stage: deploy
  <<: *base_deploy
  environment:
    name: stage
    url: https://hack.dline-rhost.ru
  only:
    refs:
      - main
  tags:
    - dl-dev

